name: digital_billboard
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  geolocator: ^10.1.0 # for getting GPS location
  http: 1.3.0 # for sending HTTP requests
  supabase_flutter: ^1.10.10 # for connecting to Supabase
  flutter_dotenv: ^5.0.2
  intl: ^0.18.0 # or the latest version
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # For linting and good coding practices

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env # Only include this if you actually have a .env file
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Add custom fonts if needed
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
